data:
    dataset: "SAR"
    image_size: 128
    channels: 1
    num_workers: 8
    data_dir: "scratch/"
    conditional: True

model:
    in_channels: 1
    out_ch: 2 # 1 if not learn_sigma(iddpm) else 2
    ch: 128
    ch_mult: [1, 1, 2, 3, 4] # 通道算子
#    ch_mult: [1, 2, 3, 4] # 通道算子
    num_res_blocks: 2
    attn_resolutions: [32,16,8]
#    attn_resolutions: [16,8] 
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    mode: train # or valid
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    name: "SAR_despeckling"
    version: "v1"
    patch_n: 4
    batch_size: 5
    n_epochs: 410
    n_iters: 200
    #snapshot_freq: 1000
    validation_freq: 160 

sampling:
    batch_size: 1
    last_only: True
    sample_type: "ddim" 
    schedule: "linear" # added
    filelist: "test.txt" # "syn_val.txt" or "real_sar_test.txt" or "syn_test.txt" or "test.txt"

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002
    amsgrad: False
    eps: 0.00000001
